### ISSUE TITLE
Problem with missing components

### ISSUE THREAD

**Issue by zen** [Toroid-io/drone-kicad-sample#1]
I'm still experimenting with drone and sample project and just came across this problem:

`Warning: component 'commit-trace' for footprint 't1' from library 'toroid-kicad' was not found
Warning: component 'C_1206_3216Metric' for footprint 'C3' from library 'Capacitor_SMD' was not found
Warning: component 'C_1206_3216Metric' for footprint 'C2' from library 'Capacitor_SMD' was not found
Warning: component 'C_1206_3216Metric' for footprint 'C1' from library 'Capacitor_SMD' was not found
Warning: component 'Molex_KK-254_AE-6410-02A_1x02_P2.54mm_Vertical' for footprint 'J2' from library 'Connector_Molex' was not found
Warning: component 'Molex_KK-254_AE-6410-02A_1x02_P2.54mm_Vertical' for footprint 'J1' from library 'Connector_Molex' was not found
Warning: component 'R_1206_3216Metric' for footprint 'R3' from library 'Resistor_SMD' was not found
Warning: component 'R_1206_3216Metric' for footprint 'R2' from library 'Resistor_SMD' was not found
Warning: component 'R_1206_3216Metric' for footprint 'R1' from library 'Resistor_SMD' was not found`

Looks like Kicad is not aware of custom components, despite the fact that they are fetched:

`+ /bin/sh -c cd /usr/share/kicad/library && git clone https://github.com/Toroid-io/toroid-kicad-library.git
Cloning into 'toroid-kicad-library'...
+ /bin/sh -c cd /usr/share/kicad/template && git clone https://github.com/Toroid-io/toroid-kicad-templates.git
Cloning into 'toroid-kicad-templates'...`

Any hints guys?

**Comment by andresmanelli** [comment]
Hello, I think that output is from `PcbDraw` script. Because there is no corresponding svg for those footprints.

Could you check that? Thanks!

**Comment by zen** [comment]
Looks like that and it's harmless for the build. I will test it with "real" boards and reopen if needed. Thanks for pointing this out.
